// Namespace Configuration Values
const ATORIA = {};


ATORIA.PERCEPTION_LABEL = {
    "sight": "ATORIA.Perception.Sight",
    "taste": "ATORIA.Perception.Taste",
    "hearing": "ATORIA.Perception.Hearing",
    "smell": "ATORIA.Perception.Smell",
    "magice": "ATORIA.Perception.Magice",
    "instinct": "ATORIA.Perception.Instinct",
}
ATORIA.SKILLS_LABEL = {
    "agility": "ATORIA.Agility",
    "balance": "ATORIA.Balance",
    "flexibility": "ATORIA.Flexibility",
    "acrobatics": "ATORIA.Acrobatics",
    "analyse": "ATORIA.Analyse",
    "insight": "ATORIA.Insight",
    "identification": "ATORIA.Identification",
    "investigation": "ATORIA.Investigation",
    "athletic": "ATORIA.Athletic",
    "hiking": "ATORIA.Hiking",
    "running": "ATORIA.Running",
    "jump": "ATORIA.Jump",
    "charisma": "ATORIA.Charisma",
    "presence": "ATORIA.Presence",
    "seduction": "ATORIA.Seduction",
    "slyness": "ATORIA.Slyness",
    "silence": "ATORIA.Silence",
    "stealth": "ATORIA.Stealth",
    "concealment": "ATORIA.Concealment",
    "dressage": "ATORIA.Dressage",
    "taming": "ATORIA.Taming",
    "riding": "ATORIA.Riding",
    "eloquence": "ATORIA.Eloquence",
    "persusasion": "ATORIA.Persusasion",
    "calming": "ATORIA.Calming",
    "provocation": "ATORIA.Provocation",
    "climbing": "ATORIA.Climbing",
    "scale": "ATORIA.Scale",
    "fall": "ATORIA.Fall",
    "spirit": "ATORIA.Spirit",
    "will": "ATORIA.Will",
    "guarding": "ATORIA.Guarding",
    "memory": "ATORIA.Memory",
    "intimidation": "ATORIA.Intimidation",
    "fear": "ATORIA.Fear",
    "authority": "ATORIA.Authority",
    "threat": "ATORIA.Threat",
    "swiming": "ATORIA.Swiming",
    "ease": "ATORIA.Ease",
    "breath-holding": "ATORIA.Breath-Holding",
    "negotiation": "ATORIA.Negotiation",
    "diplomacy": "ATORIA.Diplomacy",
    "bargaining": "ATORIA.Bargaining",
    "reflex": "ATORIA.Reflex",
    "evasion": "ATORIA.Evasion",
    "opportuneness": "ATORIA.Opportuneness",
    "sturdiness": "ATORIA.Sturdiness",
    "force": "ATORIA.Force",
    "tenacity": "ATORIA.Tenacity",
    "fortitude": "ATORIA.Fortitude",
    "trickery": "ATORIA.Trickery",
    "acting": "ATORIA.Acting",
    "lying": "ATORIA.Lying",
}

ATORIA.KNOWLEDGES_LABEL = {
    "alchemy": "ATORIA.Alchemy",
    "jewellery": "ATORIA.Jewellery",
    "sewing": "ATORIA.Sewing",
    "cabinet-making": "ATORIA.Cabinet-making",
    "forge": "ATORIA.Forge",
    "engineering": "ATORIA.Engineering",
    "leatherworking": "ATORIA.Leatherworking",
    "song": "ATORIA.Song",
    "dance": "ATORIA.Dance",
    "graphic": "ATORIA.Graphic",
    "music": "ATORIA.Music",
    "sculpture": "ATORIA.Sculpture",
    "civilisation": "ATORIA.Civilisation",
    "language": "ATORIA.Language",
    "medecine": "ATORIA.Medecine",
    "monstrology": "ATORIA.Monstrology",
    "science": "ATORIA.Science",
    "symbolism": "ATORIA.Symbolism",
    "zoology": "ATORIA.Zoology",
    "farming": "ATORIA.Farming",
    "livestock": "ATORIA.Livestock",
    "herbalist": "ATORIA.Herbalist",
    "mining": "ATORIA.Mining",
    "fishing": "ATORIA.Fishing",
    "hunting": "ATORIA.Hunting",
    "construction": "ATORIA.Construction",
    "cuisine": "ATORIA.Cuisine",
    "game": "ATORIA.Game",
    "strategy": "ATORIA.Strategy",
    "vehicle": "ATORIA.Vehicle",
    "theft": "ATORIA.Theft",
}
ATORIA.MAGICS_LABEL = {
    "mental": "ATORIA.Mental",
    "holy": "ATORIA.Holy",
    "fire": "ATORIA.Fire",
    "water": "ATORIA.Water",
    "air": "ATORIA.Air",
    "earth": "ATORIA.Earth",
    "blood": "ATORIA.Blood",
    "occult": "ATORIA.Occult",
    "druidic": "ATORIA.Druidic",
    "invoker": "ATORIA.Invoker"
}

export default ATORIA;